apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghmeh-gui-deployment
  labels:
    app: loghmeh-gui
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: loghmeh-gui
  template:
    metadata:
      labels:
        app: loghmeh-gui
    spec:
      containers:
      - name: loghmeh-gui
        image: alirezasalemi/loghmeh-gui
        resources:
          limits:
            memory: "100Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        imagePullPolicy: Always
