apiVersion: v1
kind: Service
metadata:
  name: loghmeh-gui-service
spec:
  selector:
    app: loghmeh-gui
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30037
  type: NodePort